CREATE TABLE repositories(repo_id TEXT PRIMARY KEY, epoch_id TEXT NOT NULL);
INSERT INTO repositories SELECT repo_id,'' FROM bindings;
CREATE TABLE bindings_new(binding TEXT PRIMARY KEY, repo_id TEXT NOT NULL REFERENCES repositories(repo_id));
INSERT INTO bindings_new SELECT * FROM bindings;
CREATE TABLE authority_new(repo_id TEXT NOT NULL REFERENCES repositories(repo_id), kind TEXT NOT NULL, PRIMARY KEY(repo_id,kind));
INSERT INTO authority_new SELECT * FROM authority;
CREATE TABLE documents_new(id TEXT PRIMARY KEY, repo_id TEXT NOT NULL REFERENCES repositories(repo_id), kind TEXT NOT NULL, locator TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision>0), content BLOB NOT NULL, deleted INTEGER NOT NULL CHECK(deleted IN (0,1)), UNIQUE(repo_id,kind,locator));
INSERT INTO documents_new SELECT * FROM documents;
CREATE TABLE migration_sources_new(repo_id TEXT NOT NULL REFERENCES repositories(repo_id), kind TEXT NOT NULL, locator TEXT NOT NULL, source_path TEXT NOT NULL, digest TEXT NOT NULL, content BLOB NOT NULL, PRIMARY KEY(repo_id,kind,locator,source_path));
INSERT INTO migration_sources_new SELECT * FROM migration_sources;
DROP TABLE bindings;
DROP TABLE authority;
DROP TABLE documents;
DROP TABLE migration_sources;
ALTER TABLE bindings_new RENAME TO bindings;
ALTER TABLE authority_new RENAME TO authority;
ALTER TABLE documents_new RENAME TO documents;
ALTER TABLE migration_sources_new RENAME TO migration_sources;
ALTER TABLE metadata ADD COLUMN replica_id TEXT NOT NULL DEFAULT '';
CREATE TABLE clocks(record_id TEXT PRIMARY KEY REFERENCES documents(id), clock TEXT NOT NULL);
PRAGMA user_version=2;
