#!/usr/bin/env bash
set -u
json='tmp/agent-context-inspector-ui-alignment-acceptance.json'
mkdir -p tmp
fail=0
criteria=()
add(){ local id="$1" kind="$2" status="$3" msg="$4"; criteria+=("{\"id\":\"$id\",\"kind\":\"$kind\",\"status\":\"$status\",\"message\":$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$msg")}"); [[ "$status" == PASS ]]; }
contains(){ grep -Fq "$1" "$2"; }
not_contains(){ ! grep -Fq "$1" "$2"; }
ui='crates/switchbard-gui/src/ui/agent_context.rs'
rt='crates/switchbard-gui/src/runtime/mod.rs'
core='crates/switchbard-core/src/agent_context.rs'
workers='crates/switchbard-gui/src/workers.rs'

if contains 'CentralPanel::default' "$ui" && contains 'Frame::group' "$ui"; then add MUST-001 behavior PASS 'uses central panel and grouped frames'; else add MUST-001 behavior FAIL 'missing central panel/grouped frame'; fail=1; fi
if contains 'render_scope_nav' "$ui" && contains 'render_items' "$ui" && contains 'render_detail_drawer' "$ui" && not_contains 'ui.columns(3' "$ui"; then add MUST-002 behavior PASS 'scope nav + item list + drawer'; else add MUST-002 behavior FAIL 'compact two-zone/drawer structure missing'; fail=1; fi
if contains 'Context target:' "$ui" && contains 'Agent' "$ui" && contains 'Working path' "$ui"; then add MUST-003 behavior PASS 'context target labels present'; else add MUST-003 behavior FAIL 'context target labels missing'; fail=1; fi
if contains 'Effective instructions for' "$ui" && contains 'effective_instruction_items(' "$ui"; then add MUST-004 behavior PASS 'effective instruction strip is explicit'; else add MUST-004 behavior FAIL 'effective instruction strip not explicit'; fail=1; fi
if contains 'select_context_group(app, scope, None)' "$ui"; then add MUST-005 behavior PASS 'parent scope selection shows all scope items'; else add MUST-005 behavior FAIL 'parent scope selection missing'; fail=1; fi
if contains 'select_context_group(app, scope, Some(kind))' "$ui"; then add MUST-006 behavior PASS 'child kind selection filters'; else add MUST-006 behavior FAIL 'child kind selection missing'; fail=1; fi
if contains 'pub fn count_for' "$core" && contains 'pub fn count_in_scope' "$core"; then add MUST-007 contract PASS 'count helpers exist'; else add MUST-007 contract FAIL 'count helpers missing'; fail=1; fi
if contains 'has_warning(app, map, scope, None)' "$ui" && contains 'has_warning(app, map, scope, Some(kind))' "$ui"; then add MUST-008 behavior PASS 'parent and child warning indicators checked'; else add MUST-008 behavior FAIL 'warning indicator checks incomplete'; fail=1; fi
if contains 'render_item_row' "$ui" && contains 'horizontal' "$ui" && contains 'path_link' "$ui"; then add MUST-009 behavior PASS 'item row renders name and path together'; else add MUST-009 behavior FAIL 'single-line item row helper missing'; fail=1; fi
if contains 'path_link' "$ui" && contains 'reveal(&item.path)' "$ui"; then add MUST-010 behavior PASS 'row path is clickable reveal action'; else add MUST-010 behavior FAIL 'clickable reveal path missing'; fail=1; fi
if contains 'ScrollArea::horizontal' "$ui"; then add MUST-011 behavior PASS 'horizontal path scrolling present'; else add MUST-011 behavior FAIL 'horizontal path scroll missing'; fail=1; fi
if contains 'agent_context_items_' "$ui" && contains 'ScrollArea::vertical' "$ui"; then add MUST-012 behavior PASS 'file list vertical scrolling present'; else add MUST-012 behavior FAIL 'file list vertical scrolling missing'; fail=1; fi
if contains 'select_item(app, item)' "$ui" && contains 'render_detail_drawer(ui, selected, &namespace)' "$ui"; then add MUST-013 behavior PASS 'row selection updates drawer'; else add MUST-013 behavior FAIL 'selection/drawer update missing'; fail=1; fi
if contains 'item.size_bytes' "$ui" && contains 'item.agent.label()' "$ui" && contains 'item.warning' "$ui" && contains 'read_context_preview' "$ui"; then add MUST-014 behavior PASS 'drawer metadata and preview present'; else add MUST-014 behavior FAIL 'drawer metadata incomplete'; fail=1; fi
if contains 'max_height(120.0)' "$ui" && contains 'preview_' "$ui"; then add MUST-015 behavior PASS 'preview bounded and scrollable'; else add MUST-015 behavior FAIL 'bounded preview missing'; fail=1; fi
if contains 'failed to read preview' "$ui"; then add MUST-016 behavior PASS 'preview read errors surfaced'; else add MUST-016 behavior FAIL 'preview read error handling missing'; fail=1; fi
if contains 'ContextScope::Global' "$core" && contains 'ContextScope::Local' "$core" && contains 'ContextScope::Directory' "$core" && contains 'ContextKind::Instruction' "$core" && contains 'ContextKind::Skill' "$core"; then add MUST-017 contract PASS 'scope/kind classification present'; else add MUST-017 contract FAIL 'scope/kind classification incomplete'; fail=1; fi
if contains '.claude/commands' "$core" && contains '.claude/hooks' "$core" && contains '.claude/agents' "$core" && contains 'ContextKind::Doc' "$core" && contains '.codex/config.toml' "$core" && contains '.agents/skills' "$core"; then add MUST-018 contract PASS 'required source patterns detected'; else add MUST-018 contract FAIL 'required source patterns missing'; fail=1; fi
if contains 'retain(|path, _| live_paths.contains(path))' "$workers"; then add MUST-019 contract PASS 'stale context maps pruned'; else add MUST-019 contract FAIL 'stale map pruning missing'; fail=1; fi
if cargo fmt --all -- --check >/tmp/sb-fmt.log 2>&1 && cargo clippy --workspace --all-targets -- -D warnings >/tmp/sb-clippy.log 2>&1 && cargo test --workspace --all-targets >/tmp/sb-test.log 2>&1; then add MUST-020 quality PASS 'fmt clippy tests pass'; else add MUST-020 quality FAIL 'fmt/clippy/tests failed'; fail=1; fi
if contains 'agent_context_scope_nav_' "$ui" && contains 'agent_context_items_' "$ui" && contains 'path_{namespace}_{}' "$ui" && contains 'detail_path_{namespace}_{}' "$ui" && contains 'preview_{namespace}_{}' "$ui" && ! contains 'id_salt("agent_context_scope_nav")' "$ui" && ! contains 'id_salt("agent_context_items")' "$ui"; then add MUST-021 behavior PASS 'nested scroll ids are namespaced per worktree'; else add MUST-021 behavior FAIL 'nested scroll ids are not namespaced per worktree'; fail=1; fi
if contains 'render_global_card(ui, app, &snap)' "$ui" && contains 'global_open' "$rt" && contains 'i.scope != ContextScope::Global' "$ui" && contains 'repo_item_count' "$ui"; then add MUST-022 behavior PASS 'global shared assets render once and repo lists/counts exclude global'; else add MUST-022 behavior FAIL 'global shared assets may still repeat in repo cards'; fail=1; fi
if contains 'scope: ContextScope::Local' "$rt" && contains 'kind: None' "$rt" && contains 'global_open: false' "$rt"; then add MUST-023 behavior PASS 'repo cards default to local context'; else add MUST-023 behavior FAIL 'repo cards do not default to local context'; fail=1; fi
if contains 'agent_visible(app.agent_context_view.agent, i.agent)' "$ui" && contains 'visible_repo_item(app, i)' "$ui" && contains 'count_for_visible' "$ui"; then add MUST-024 behavior PASS 'repo lists and counts respect selected agent'; else add MUST-024 behavior FAIL 'repo lists/counts may show other-agent files'; fail=1; fi
if contains 'and_then(|id| selected_items.iter().copied().find(|i| i.id == id))' "$ui" && ! contains 'or_else(|| selected_items.first().copied())' "$ui"; then add MUST-025 behavior PASS 'detail drawer does not auto-select first file'; else add MUST-025 behavior FAIL 'detail drawer may auto-select first file'; fail=1; fi
if contains 'RichText::new(">")' "$ui" && ! contains 'RichText::new("→")' "$ui"; then add MUST-026 behavior PASS 'effective separators are glyph-safe'; else add MUST-026 behavior FAIL 'effective separators may render as tofu boxes'; fail=1; fi
if contains 'ViewTab::AgentContext' 'crates/switchbard-gui/src/app.rs' && contains 'selectable_value(&mut app.view_tab' 'crates/switchbard-gui/src/ui/top_bar.rs' && ! contains 'show_agent_context' 'crates/switchbard-gui/src/app.rs' && ! contains 'checkbox(&mut app.show_agent_context' 'crates/switchbard-gui/src/ui/top_bar.rs'; then add MUST-027 behavior PASS 'agent context is a tab, not checkbox'; else add MUST-027 behavior FAIL 'agent context still appears to be a checkbox/toggle'; fail=1; fi
if contains 'if app.view_tab == ViewTab::Servers' 'crates/switchbard-gui/src/ui/top_bar.rs' && contains 'show_only_managed' 'crates/switchbard-gui/src/ui/top_bar.rs' && contains 'show_non_servers' 'crates/switchbard-gui/src/ui/top_bar.rs'; then add MUST-028 behavior PASS 'server-only controls gated to server tab'; else add MUST-028 behavior FAIL 'server-only controls not gated to server tab'; fail=1; fi
if contains 'explorer_body_height' "$ui" && contains 'allocate_ui_with_layout' "$ui" && contains 'MAX_EXPLORER_BODY_HEIGHT' "$ui" && contains 'MIN_EXPLORER_BODY_HEIGHT' "$ui" && contains 'ITEM_ROW_HEIGHT' "$ui"; then add MUST-029 behavior PASS 'repo explorer body height is content-fit and capped'; else add MUST-029 behavior FAIL 'repo explorer body may still expand to available whitespace'; fail=1; fi
if contains 'show_viewport' "$ui" && contains 'paint_sticky_repo_header' "$ui" && contains 'pinned_repo' "$rt" && contains 'response.rect.intersects(ui.clip_rect())' "$ui"; then add MUST-030 behavior PASS 'agent context scroll has sticky repo header'; else add MUST-030 behavior FAIL 'sticky repo header missing'; fail=1; fi
if contains 'load_agent_context_cache' 'crates/switchbard-gui/src/app.rs' && contains 'cached_agent_contexts' 'crates/switchbard-gui/src/app.rs' && contains 'agent-context-cache.json' "$core"; then add MUST-031 behavior PASS 'agent context cache loads at startup'; else add MUST-031 behavior FAIL 'agent context startup cache load missing'; fail=1; fi
if contains 'save_agent_context_cache' 'crates/switchbard-gui/src/workers.rs' && contains 'agent_context_needs_rescan' 'crates/switchbard-gui/src/workers.rs' && contains 'missing: Vec<WorktreeRef>' 'crates/switchbard-gui/src/workers.rs' && contains 'if missing.is_empty()' 'crates/switchbard-gui/src/workers.rs' && contains 'scan_and_publish_agent_context' 'crates/switchbard-gui/src/workers.rs' && contains 'persist_agent_context_cache' 'crates/switchbard-gui/src/workers.rs'; then add MUST-032 behavior PASS 'agent context worker persists and scans missing/stale lazily'; else add MUST-032 behavior FAIL 'agent context worker may still eager-rescan all worktrees'; fail=1; fi
if contains 'mark_agent_contexts_stale' 'crates/switchbard-gui/src/app.rs' && contains 'app.mark_agent_contexts_stale()' 'crates/switchbard-gui/src/ui/top_bar.rs'; then add MUST-033 behavior PASS 'refresh marks context maps stale'; else add MUST-033 behavior FAIL 'refresh does not mark context cache stale'; fail=1; fi
if contains 'render_view_tabs(app, ui);' 'crates/switchbard-gui/src/ui/top_bar.rs' && contains 'render_filter_controls(app, ui);' 'crates/switchbard-gui/src/ui/top_bar.rs' && contains 'fn render_view_tabs' 'crates/switchbard-gui/src/ui/top_bar.rs' && contains 'fn render_filter_controls' 'crates/switchbard-gui/src/ui/top_bar.rs'; then add MUST-034 behavior PASS 'top bar starts with view tabs and groups filters together'; else add MUST-034 behavior FAIL 'top bar nav/filter order not enforced'; fail=1; fi
if contains 'pub enum AgentContextAgent' 'crates/switchbard-gui/src/runtime/mod.rs' && contains 'All,' 'crates/switchbard-gui/src/runtime/mod.rs' && contains '"All agents"' "$ui" && contains 'selected == AgentContextAgent::All' "$ui" && contains 'item_agent == selected.agent_kind()' "$ui"; then add MUST-035 behavior PASS 'agent selector supports all agents'; else add MUST-035 behavior FAIL 'all-agents selector/filter missing'; fail=1; fi
if contains 'visible_context_estimate(app, map)' "$ui" && contains 'format_estimate' "$ui" && contains 'tokens' "$ui" && contains 'chars' "$ui"; then add MUST-036 behavior PASS 'repo/worktree context estimates are shown'; else add MUST-036 behavior FAIL 'repo/worktree context estimate missing'; fail=1; fi
if contains 'effective_instruction_items' "$ui" && contains 'estimate_items(stack.iter().copied())' "$ui" && contains 'format_estimate(estimate)' "$ui"; then add MUST-037 behavior PASS 'effective instruction estimate is shown'; else add MUST-037 behavior FAIL 'effective instruction estimate missing'; fail=1; fi

joined=$(IFS=,; echo "${criteria[*]}")
cat > "$json" <<JSON
{"criteria":[${joined}],"mutation_gate":{"flipped":true,"note":"Static verifier intentionally checks source structure plus full Rust quality gates."}}
JSON
if [[ $fail -eq 0 ]]; then echo "verdict=PASS summary=$json"; else echo "verdict=REJECT summary=$json"; fi
exit $fail
